---
title: "1.3 Task 3 - Sea bird observation data"
output: html_notebook
---
```{r}
library(tidyverse)
library(readxl)
ship_data_by_record <- read_excel("/Users/mahri/Documents/codeClan_docs/dirty_data_codeclan_project_mahri/dirty_data_project_raw_data/seabirds.xls")
bird_data_by_record <- read_excel("raw_data/seabirds.xls", sheet = 2)
ship_data_codes <- read_excel("raw_data/seabirds.xls", sheet = 3)
bird_data_codes <- read_excel("raw_data/seabirds.xls", sheet = 4)
```

```{r}
#no meta data to remove 

glimpse(ship_data_by_record)
# 27 cols, 12,310 rows 

glimpse(bird_data_by_record)
# 26 cols, 49,019 rows

names(ship_data_by_record)
names(bird_data_by_record)
# both have RECORD and RECORD ID 

```

```{r}
library(janitor)

ship_data_records <- janitor::clean_names(ship_data_by_record)
bird_data_records <- janitor::clean_names(bird_data_by_record)

ship_data_records
bird_data_records

bird_data_renamed <- bird_data_records %>%
  rename("species_common_name" = "species_common_name_taxon_age_sex_plumage_phase", "species_scientific_name" = "species_scientific_name_taxon_age_sex_plumage_phase", "birds_counted" = "count")

ship_data_renamed <- ship_data_records %>% 
  rename("latitude" = "lat", "longitude" = "long")

bird_data_renamed %>%
  names()

bird_data_renamed %>%
  summarise(count = sum(is.na(birds_counted)))
# 2699 NAs in bird count column 

ship_data_renamed %>% 
  summarise(count = sum(is.na(latitude)))
# 10 missing latitudes 


bird_data_renamed %>% 
  group_by(species_scientific_name) %>% 
  count(species_scientific_name)
# 311 rows -- including "NA n=1101"

bird_data_renamed %>% 
  group_by(species_common_name) %>% 
  count(species_common_name)
# 322 rows -- including "[NO BIRDS RECORDED] n=691" 

bird_data_renamed %>% 
  group_by(species_abbreviation) %>% 
  count(species_abbreviation)
# 321 rows -- inlcuding "NA n=691"

# PLAN 
#
# Get rid of a bunch of unnecessary columns
# SHIPS - KEEP: "record"    "record_id" "date" "time" "latitude"  
# "longitude" (What do we think long360, latcell, and longcell mean??)
# BIRDS KEEP -"record" "record_id" "species_common_name" "species_scientific_name"
# "species_abbreviation" "birds_counted" 
# 
# Join both tables together by record ID but remember there is 1 record 
# ID for ships but multiple IDs in birds as they spotted more than one species
# on each sighting.

# Remove NAs and No Birds Recorded

# obviously sort cleaning into a R file, and analysis in here. 
```

